name: Update All Submodules

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update all submodules to latest commit
        run: |
          git fetch origin
          git checkout -B "${{ github.ref_name }}" "origin/${{ github.ref_name }}" || true
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git add -A
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "chore: update all submodules to latest commits" || echo "No changes to commit"
          git push origin HEAD:refs/heads/${{ github.ref_name }} || echo "Push failed — check branch protection and workflow permissions"
